language: node_js
node_js: 
  - "iojs"

branches:
  only:
  - source

cache:
  directories:
      - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_ab1b0c1283a6_key -iv $encrypted_ab1b0c1283a6_iv
  -in travis.key.enc -out travis.key -d
- chmod 600 ~/.ssh/id_rsa
- git config --global username "qiu"
- git config --global user.emal "q974514569@gmail.com"

install:
- npm install gitbook-cli

script:
- gitbook install
- gitbook build

addons:
    ssh_known_hosts: 198.199.85.208:2333

after_success:
- git remote add origin ssh://git@vps2:2333/home/git/srv/sample.git
- git push -u vps master:master


  
